### ISSUE TITLE
have you tried integrating mxstbr/react-boilerplate with erikras/redux-form?

### ISSUE THREAD

**Issue by katcu** [Iuriy-Budnikov/shopify_visivisor#1]
Sry, can not connect you in other ways, so just post here :ghost: 

I still got nothing help from the repositories contributors :disappointed: 
I even have migrated my project components code into the `mxstbr/react-boilerplate`. And now I can not use other awesome modules(`redux-form` as mentioned, and 
`mjrussell/redux-auth-wrapper`, etc ) with it, that's really awful! I've also posted a issue on the `mxstbr/react-boilerplate` to mention this.  Could you help me please with this? Greatly appreciated!

**Comment by Iuriy-Budnikov** [comment]
Hey @katcu Ok, i will be able to help you tomorrow.

**Comment by katcu** [comment]
@Iuriy-Budnikov   thank You  so much!!!!!!!!!!
